### ISSUE TITLE
No application associated with file type

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/ModdersToolkit#2]
If .cs files don't have a file association, errors can occur.
![](https://i.imgur.com/dSqBGyp.png)

**Comment by Agrair** [comment]
Check these links on how to fix that:
[MacOS](https://www.dummies.com/computers/macs/mac-operating-systems/how-to-assign-a-file-type-to-an-application-in-mac-os-x-lion/)
[Win7](https://support.microsoft.com/en-us/help/18539/windows-7-change-default-programs)
[Win8](https://www.cnet.com/how-to/how-to-change-default-programs-in-windows-8/)
[Win10](https://www.lifewire.com/how-to-change-file-associations-in-windows-2624477)
[Ubuntu](https://help.ubuntu.com/stable/ubuntu-help/files-open.html.en)
[Mint](https://forums.linuxmint.com/viewtopic.php?t=252221)
Disclaimer: I do not understand any of the terminology used in the links for Linux distros, it may not be the appropriate site.
